### ISSUE TITLE
Cannot create cookie on host with non-standard port number

### ISSUE THREAD

**Issue by gabrielf** [fcapano/Edit-This-Cookie#100]
Hi, this old issue https://github.com/fcapano/Edit-This-Cookie/issues/32 still exists. You cannot set cookies with a port in the domain. This is how cookies work. Edit This Cookie should strip the port number from the host when pre-filling the domain name.

**Comment by PalleZingmark** [comment]
+1 to @gabrielf 
This is really annoying, forcing me to use other solutions for those projects using ports.

**Comment by kahlin** [comment]
+1

This has caused me some confusion as well.

**Comment by halilim** [comment]
+1, this is required for many frameworks.

**Comment by JHK** [comment]
+1, yep, really annoying

**Comment by ritwikSOP** [comment]
+1

**Comment by clintonb** [comment]
This remains an issue with version 1.4.1 for Chrome 54.0.2840.98 (64-bit) on macOS.
