### ISSUE TITLE
cookies

### ISSUE THREAD

**Issue by le2ruote** [fcapano/Edit-This-Cookie#121]
Ciao,  avrei bisogno del tuo aiuto, spero tu possa darmelo. 
Premetto che non sono un programmatore, nella vita faccio altro.
ho realizzato però un sito grazie ad un cms che si chiama panda resort,  mi serve per un albergo.
purtroppo ho notato che non c'è un plugin preimpostato per i cookies come per wordpress. 
Volevo chiederti se potevi aiutarmi a comprendere come istallare i cookies sul mio sito.
vorrei capire come e dove vanno caricate le cartelle tramite filezilla, ed anche il setup.
spero tu riesca ad aiutarmi.
grazie.

**Comment by solocommand** [comment]
@le2ruote You'd need to contact your software vendor's support team for questions about changing cookie settings within their CMS. This repository is for a browser extension to manage cookies/
