### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by josepitateamcmp** [fcapano/Edit-This-Cookie#132]
Would be very helpful to be able to save an edited cookie just by hitting the enter key.
Right now, when I'm editing a cookie, I press Enter and it goes down one line.
If not all the users want this, would be nice to have a checkbox with an option "Save changes on Enter"

**Comment by fieteboerner** [comment]
Look at my pull request #133. With this Keystroke `ctrl+return` you can save changes much more faster then using the mouse.

**Comment by josepitateamcmp** [comment]
@fieteboerner awesome!
