### ISSUE TITLE
Feature Request: Copy Cookie as String

### ISSUE THREAD

**Issue by jordonbiondo** [fcapano/Edit-This-Cookie#137]
I've been looking for an extension to copy the current cookie as it's semicolon separated string value. 

I've been using a special tool to transform the json from Edit-This-Cookie into an actual cookie string for use but I'd prefer to be able to copy it directly. 

Perhaps the export button could have a drop down with additional format options.

**Comment by fcapano** [comment]
The option already exists in the extension's options. Currently you can choose beftween four different formats among which a colon separated name=value string
