### ISSUE TITLE
Netflix

### ISSUE THREAD

**Issue by dolape20** [fcapano/Edit-This-Cookie#146]
[
{
"domain": ".netflix.com",
"expirationDate": 3631142871.827592,
"hostOnly": false,
"httpOnly": false,
"name": "dsca",
"path": "/",
"sameSite": "no_restriction",
"secure": false,
"session": false,
"storeId": "0",
"value": "customer",
"id": 1
},
{
"domain": ".netflix.com",
"expirationDate": 1484035154.775437,
"hostOnly": false,
"httpOnly": false,
"name": "lhpuuidh-browse-4VBMBHUZ5BDBRJDEB46H7JKJ74",
"path": "/",
"sameSite": "no_restriction",
"secure": false,
"session": false,
"storeId": "0",
"value": "MX%3AEN-GB%3Ad0a59644-5bbe-44d8-9fb4-568b6e2f5dad_ROOT",
"id": 2
},
{
"domain": ".netflix.com",
"expirationDate": 1484035349.351802,
"hostOnly": false,
"httpOnly": false,
"name": "lhpuuidh-browse-DR5T26HDGBGCRBE4Z3GVTONEVU",
"path": "/",
"sameSite": "no_restriction",
"secure": false,
"session": false,
"storeId": "0",
"value": "MX%3AEN-GB%3A88a2d067-d470-4aeb-94c5-b680fdc26981_ROOT",
"id": 3
},
{
"domain": ".netflix.com",
"expirationDate": 1484035205.226997,
"hostOnly": false,
"httpOnly": false,
"name": "lhpuuidh-browse-L3ICYOSRFRD57GHQZJ6F3P3WPE",
"path": "/",
"sameSite": "no_restriction",
"secure": false,
"session": false,
"storeId": "0",
"value": "MX%3ANB-NO%3A15e47877-4a71-48f8-8623-a6871ce952ad_ROOT",
"id": 4
},
{
"domain": ".netflix.com",
"expirationDate": 1484035253.448997,
"hostOnly": false,
"httpOnly": false,
"name": "lhpuuidh-browse-NRQOGXXVBJCOJH5WAAJ4TFIXJI",
"path": "/",
"sameSite": "no_restriction",
"secure": false,
"session": false,
"storeId": "0",
"value": "MX%3AEN-US%3A25719f88-5d95-4413-a62f-ca469ebc2ada_ROOT",
"id": 5
},
{
"domain": ".netflix.com",
"expirationDate": 1484035299.795101,
"hostOnly": false,
"httpOnly": false,
"name": "lhpuuidh-browse-SUO47ZKI35GR5ERNSOUFWZ6I3U",
"path": "/",
"sameSite": "no_restriction",
"secure": false,
"session": false,
"storeId": "0",
"value": "MX%3AES-CL%3A45bd0af8-d84d-4fbf-aba1-f9017d1c3ad6_ROOT",
"id": 6
},
{
"domain": ".netflix.com",
"expirationDate": 1484029553,
"hostOnly": false,
"httpOnly": false,
"name": "lhpuuidh-browse-VVQYBG3NOVG7XAK54DULXNT7JM",
"path": "/",
"sameSite": "no_restriction",
"secure": false,
"session": false,
"storeId": "0",
"value": "MX%3AEN-US%3A25dab390-fecb-454d-82ab-67ac69c7a1b3_ROOT",
"id": 7
},
{
"domain": ".netflix.com",
"expirationDate": 1484410114,
"hostOnly": false,
"httpOnly": false,
"name": "lhpuuidh-browse-XJZQ75WQTNDYXEEIHBC5ZHRZEI",
"path": "/",
"sameSite": "no_restriction",
"secure": false,
"session": false,
"storeId": "0",
"value": "PE%3APT-BR%3A7944e352-59b8-4761-9598-1279a54ed083_ROOT",
"id": 8
},
{
"domain": ".netflix.com",
"expirationDate": 1515535354.933801,
"hostOnly": false,
"httpOnly": false,
"name": "memclid",
"path": "/",
"sameSite": "no_restriction",
"secure": false,
"session": false,
"storeId": "0",
"value": "7d6a13b3-49c6-4558-a7fd-66ab2b9651cf",
"id": 9
},
{
"domain": ".netflix.com",
"hostOnly": false,
"httpOnly": true,
"name": "NetflixId",
"path": "/",
"sameSite": "no_restriction",
"secure": false,
"session": true,
"storeId": "0",
"value": "ct%3DBQAOAAEBEDXWlumPuB146uskGKVsihOB0Now978DH0nZTNazTtrOKtwH_9ILqmZewcvI3RVvvcFDGx5ve78d2QOC2QcAUlXKRQvyZy37j7tC-0D3euzBQ45kE3vHwNjSlY9z_MQ7--i3tDtEOKwz-zDjHMRw3m7pXIuB-6BR6M8-z1ae0WGyCw1QsAdLVziW4icmsGBtdVz5zwrHDot9SkZks7Sa8wXAgSRYQft5Z9nVErkP3kCdisYTdeldYytEaybNbSa7-AaCSnwzvQgd7aNWoTlXI35Kkeqi01kMWQz7wkXTu7C3heA6CzH7GgajRjwobH-I2WZ9wYR0aQAOL_r8JvXBWdkeo-JbZSGXGNzh0o9K7LuLn3U5TbqI0F1V81oq48UC05TZ0Fqz5CaCq5-ULCJ7cJe5DH5SH-bUP5Zgq6wsXbkCaut5DVY56Fvh36iKqXpV7b3F1o3wn1Hf2q9npiLWrGEcfz-zagTcYmKbNi5-cwbqmgcEfwoX4p9R_8Ip46TV3TyBL4wOQT2jsHUTzUDD7qbq5PIPdMLu8QVpSNWMnayfH48pitOdDUbKwQYaVk50od4tf2_BnMJiTTZHUp5opkBQWTU-2DHAMav4Laa9zSH2qFqj1sV_rn4x_LN1KmWVcOcm%26bt%3Ddbl%26ch%3DAQEAEAABABQPlY0qIcd7F8iF1BH8OsO23YsfMk0ScfQ.%26v%3D2%26mac%3DAQEAEAABABS4S9mJHP3xjGOx5CRdTfuRLIkMe95Bs0c.",
"id": 10
},
{
"domain": ".netflix.com",
"expirationDate": 1515535348.866802,
"hostOnly": false,
"httpOnly": false,
"name": "nfvdid",
"path": "/",
"sameSite": "no_restriction",
"secure": false,
"session": false,
"storeId": "0",
"value": "BQFmAAEBEEFTW7%2BXm5G3EZPMDy4dcfBgRosAiIfKq8g1I%2B3PRleRyrFK4wcx%2F%2BeS0FTgMG8yTASPZSf9bX30A%2FPOLlz9WirO704OjDk4pKPG6oO52moYux%2FFlqxKvACEiPH1d%2BS89P%2FT4RRj2fobLh3Th6L7lgzt",
"id": 11
},
{
"domain": ".netflix.com",
"expirationDate": 1738389600,
"hostOnly": false,
"httpOnly": false,
"name": "nkufiLoaded",
"path": "/",
"sameSite": "no_restriction",
"secure": false,
"session": false,
"storeId": "0",
"value": "true",
"id": 12
},
{
"domain": ".netflix.com",
"expirationDate": 1484001154.224801,
"hostOnly": false,
"httpOnly": false,
"name": "profilesNewSession",
"path": "/",
"sameSite": "no_restriction",
"secure": false,
"session": false,
"storeId": "0",
"value": "0",
"id": 13
},
{
"domain": ".netflix.com",
"hostOnly": false,
"httpOnly": true,
"name": "SecureNetflixId",
"path": "/",
"sameSite": "no_restriction",
"secure": true,
"session": true,
"storeId": "0",
"value": "v%3D2%26mac%3DAQEAEQABABTyah1vDkjX8jm9X2YGH7DaQL3o4cysSxI.%26dt%3D1483999343436",
"id": 14
},
{
"domain": ".www.netflix.com",
"hostOnly": false,
"httpOnly": false,
"name": "cL",
"path": "/",
"sameSite": "no_restriction",
"secure": false,
"session": true,
"storeId": "0",
"value": "1483999347823%7C14839993293710476%7C148399932949638868%7C%7C6%7C5BR6I6PN4ZAH3AI5NXPSUGS33Q",
"id": 15
}
]

**Comment by bf4** [comment]
@dolape20 I don't think you meant to post this here... you should probably change your password

**Comment by getsadzeg** [comment]
What the hell?
