### ISSUE TITLE
Firefox Port

### ISSUE THREAD

**Issue by heubergen** [fcapano/Edit-This-Cookie#151]
Hi @fcapano 

Firefox seems to have a cookie API which you may could use to port the extension to Firefox with the WebExtensions-API. It would be great to have a better Cookie manager on Firefox that use the new API.

You find the documentation about the cookie API here: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/cookies

Best
- @heubergen

**Comment by fcapano** [comment]
A very basic port has been published for Firefox. Please keep in mind things are bound to be broken and it hasn't been thoroughly tested
https://addons.mozilla.org/en-GB/firefox/addon/editthiscookieaddon/

**Comment by heubergen** [comment]
Looks promising, I'm gone close this issue as there's a version on AMO.

**Comment by MikkCZ** [comment]
@fcapano What is the current status of the Firefox port, please? Seems it is not updated on AMO since May. I have tried to install the code from master via `about:debugging` and it seems to work. Is there any known incompatibility or anything that block publishing the add-on on AMO regularly?

**Comment by MikkCZ** [comment]
@fcapano The review process on AMO has been changed. WebExtensions are now approved automatically within minutes and the manual review follows later independently on the update publishing. I will be happy to help&test if you need.
