### ISSUE TITLE
Why is the Chrome/ium extension 3 years old?

### ISSUE THREAD

**Issue by C0rn3j** [fcapano/Edit-This-Cookie#154]
There's been 16 commits in the last 3 years, some of them supposed to fix some issues, why does the Chromium store claim it's been last updated on 2014?

Additional Information
Version: 1.4.1
Updated: September 28, 2014

**Comment by fcapano** [comment]
Hi @C0rn3j 
the honest answer is that I've been ~~quite busy~~ lazy :)
In the coming days I'll do some cleanup, update the translations and push it to the chrome web store

**Comment by djbclark** [comment]
Thanks! Looking forward to it. FYI I cloned the repo and dragged over to chrome to install, but for some reason when installed via this method none of the control widgets are visible - see screenshot:

![install via github - no widgets](https://user-images.githubusercontent.com/131936/28636349-dac2cb08-720b-11e7-9ba3-ae6522c1849a.png)
