### ISSUE TITLE
Options page checkbox is not shown

### ISSUE THREAD

**Issue by RandomOS** [fcapano/Edit-This-Cookie#165]
Platform
OS: Win7 x64
Chrome 61.0.3163.79 64bit
EditThisCookie 1.4.2
![2017-09-24_224607](https://user-images.githubusercontent.com/2714125/30783719-51f8c1f8-a17a-11e7-8fc4-d734deb3b0e5.jpg)
![2017-09-24_224901](https://user-images.githubusercontent.com/2714125/30783734-9f07809c-a17a-11e7-8d23-e97f4861a31a.jpg)

EditThisCookie 1.4.1 works fine, Please check out.

**Comment by samsmarthx** [comment]
Having the same issue.

**Comment by cslinmiso** [comment]
same here @@

**Comment by moribellamy** [comment]
same issue. just installed this extension for the first time. here is my chrome info:


Google Chrome | 62.0.3202.94 (Official Build) (64-bit) (cohort: Stable)
-- | --
Revision | 4fd852a98d66564c88736c017b0a0b0478e885ad-refs/branch-heads/3202@{#789}
OS | Windows
JavaScript | V8 6.2.414.42
Flash | 27.0.0.187 C:\Users\mori\AppData\Local\Google\Chrome\User Data\PepperFlash\27.0.0.187\pepflashplayer.dll
User Agent | Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
