### ISSUE TITLE
Not working across multiple Chrome windows

### ISSUE THREAD

**Issue by nzgeek** [fcapano/Edit-This-Cookie#167]
**OS:** Windows 10  x64 version 1607 (14393.1715)
**Browser:** Chrome 61.0.3163.100 (Official Build) (64-bit)
**EditThisCookie version:** 1.4.2

**Expected behaviour:**
If you have multiple Chrome windows open, EditThisCookie shows the cookies for the current tab in the current window.

**Observed behaviour:**
If you have multiple Chrome windows open, EditThisCookie ignores which window is active and only looks at the current tab in a specific browser window. This specific window is typically the first one opened when Chrome started.

**Example:**
![image](https://user-images.githubusercontent.com/1570303/31473083-d0d042f8-af4e-11e7-8d57-e8c3bcda999d.png)

The Chrome window in the background is the first browser window opened, and the active tab is displaying a page on The Register (www.theregister.co.uk). The foreground window was opened afterwards and has a single tab that's opened to the Google site (www.google.co.nz).

Even though the current tab in the current window is Google, EditThisCookie is showing the cookies for The Register.

**Comment by minyoungk** [comment]
I have the same issue.

**Comment by pkquell** [comment]
Me too..

**Comment by crea1** [comment]
This is not only related to Windows, I have the same issue on Linux
**OS:** Red Hat Enterprise Linux Server release 7.4
**Chrome:** Version 62.0.3202.75 (Official Build) (64-bit)
**EditThisCookie:** 1.4.2

**Comment by bayotop** [comment]
Same issue on:
Windows 10 1703 (15063.786) x64
Chrome Version 63.0.3239.108 (Official Build) (64-bit)
EditThisCookie 1.4.2

Is this project still maintained? This issue makes the extension unusable so I wonder how it is still not fixed after 2 months.

**Comment by rick-rheo** [comment]
It seems this project has been abandoned unfortunately.

**Comment by bayotop** [comment]
I am not able to reproduce the issue with EditThisCookie version 1.4.1 on latest Chrome. Unfortunately, I couldn't find the change log for 1.4.1 -> 1.4.2 so I am not sure if downgrading is a viable option. I'll look closer into this and post updates afterwards.

**Comment by bayotop** [comment]
Create a PR that addresses the issue. (#192)
