### ISSUE TITLE
No export on Linux 

### ISSUE THREAD

**Issue by djizuss** [fcapano/Edit-This-Cookie#172]
Firefox 58.0a1 Xubuntu 16.04 multiple-clipboard Diodon
https://launchpad.net/diodon
No export

**Comment by Ramblurr** [comment]
I'm on 57.0 on Fedora linux with Wayland and this extension doesn't put anything in the clipboard when clicking the export button.

**Comment by fcapano** [comment]
This issue is not limited to Linux. See #179
