### ISSUE TITLE
EditThisCookie Extension : Options without Check-Buttons?

### ISSUE THREAD

**Issue by Clemens-Ratte-Polle** [fcapano/Edit-This-Cookie#173]
i dont see any possibilities to checkout the options on the lefthand side...
Could another extension block these graphics?

![extension editthiscookie options error no buttons 2017-11-13_140956](https://user-images.githubusercontent.com/10136291/32728605-3919025a-c881-11e7-9451-026d35c966bb.png)

**Comment by John-Mikael** [comment]
I have the same issue too. Check boxes for cookies info are also missing:
![image1](https://user-images.githubusercontent.com/33954530/33205322-cc6e6eb8-d106-11e7-8631-f41f410bdc45.png)
