### ISSUE TITLE
EditThisCookie Extension : German Translation wrong

### ISSUE THREAD

**Issue by Clemens-Ratte-Polle** [fcapano/Edit-This-Cookie#174]
The german translation is wrong:
English : Block Cookie
wrong German : Markieren Sie dies Cookie. This means "Mark this Cookie", which is wrong.
correct German: Blockieren Sie dies Cookie - Short: Cookie blockieren  

![extension editthiscookie markieren wrong blockieren richtig 2017-11-13_140956](https://user-images.githubusercontent.com/10136291/32728645-5f08cb62-c881-11e7-943a-eac93056b55f.png)

There are yet more doubtful german translations, so i will switch to english :)

**Comment by fcapano** [comment]
Hi @Clemens-Ratte-Polle, the extension is localized by its users.
I would really appreciate if you could dedicate some time to review the doubtful translations here: https://www.getlocalization.com/editthiscookie

Thanks in advance!
