### ISSUE TITLE
The popup window height sometimes is very small

### ISSUE THREAD

**Issue by wuhao-ouyang** [fcapano/Edit-This-Cookie#177]
<img width="563" alt="screen shot 2017-11-21 at 11 41 55 am" src="https://user-images.githubusercontent.com/8482578/33093299-7d97ff86-ceb1-11e7-832e-2b805e63c7f4.png">
On my mac, when I click the extension icon, the popup window sometimes shows up very tiny.

**Comment by deglavs** [comment]
Yes, same issue on my Mac (Chrome browser). It's very annoying. You have to click repeatedly until it finally opens up properly. I used to right click when this happened, and there were 2 EditThisCookie menu entries, and when I clicked on the second one, it opened the popup in a new tab properly. Now, there is only one menu entry and that opens "http://www.editthiscookie.com/" web page.

**Comment by hiburn8** [comment]
If you click the green tick icon when this happens the menu will reload and display fully. I have had this issue for probably 2 years.

**Comment by fcapano** [comment]
This issue is a duplicate of #203

**Comment by hiburn8** [comment]
Er no... #203 is a duplicate of this :P
