### ISSUE TITLE
Export not copying to clipboard

### ISSUE THREAD

**Issue by kenneth-k** [fcapano/Edit-This-Cookie#179]
Firefox 57.0 (64-bit)
MacOS High Sierra 10.13.1
Edit-This-Cookie 1.5.1

When I hit export, the clipboard is unchanged.  Sounds like a permissions problem.  If an easy fix is not possible, I suggest opening a dialog I can actively copy the content.

**Comment by vx-github** [comment]
Same problem on Linux:
Firefox 57.0 (64-bit)
Fedora 25 - firefox.x86_64 57.0-2.fc25
Edit-This-Cookie 1.5.1

**Comment by geekslider** [comment]
same here :(    But it will work on chrome.

**Comment by kenneth-k** [comment]
Was this ever published to Mozilla?  I can't find a version 1.5.9, or any
version for that matter.
