### ISSUE TITLE
No cookies here! shown on all sites

### ISSUE THREAD

**Issue by aoster-cq** [fcapano/Edit-This-Cookie#187]
Hi,

A few weeks ago Edit This Cookie was working fine on my Mac. Now, every site says No cookies here! Any idea what might have gone wrong?

I'm running Mac OS High Sierra and the latest version of Chrome.

**Comment by bayotop** [comment]
Probably related to: https://github.com/fcapano/Edit-This-Cookie/issues/167

**Comment by fcapano** [comment]
Yes, as @bayotop said it seems related to #167.
The next update in the Chrome Web Store (1.4.3) should fix the issue
