### ISSUE TITLE
EditThisCookie wont show cookies for roblox

### ISSUE THREAD

**Issue by EtisalatPlaysMC** [fcapano/Edit-This-Cookie#188]
EDIT THIS COOKIE DOESNT SHOWS COOKIES WHEN IAM IN ROBLOX.COM ITS ONLY SHOWS google and stuff idk why

**Comment by bayotop** [comment]
Probably related to: https://github.com/fcapano/Edit-This-Cookie/issues/167

**Comment by fcapano** [comment]
Yes, as @bayotop said it seems related to #167.
The next update in the Chrome Web Store (1.4.3) should fix the issue
