### ISSUE TITLE
Can only see the bottom part

### ISSUE THREAD

**Issue by ajouve** [fcapano/Edit-This-Cookie#203]
<img width="554" alt="screen shot 2018-03-28 at 12 41 51" src="https://user-images.githubusercontent.com/2337492/38024590-cef44a28-3285-11e8-907e-d2e2a788336b.png">

I only see this part of the window, I am using chrome on macbook, let me know if you want more details

**Comment by dunklesToast** [comment]
Same here - when clicking the green check-icon the date just switches

**Comment by fcapano** [comment]
@ajouve @dunklesToast 
- What version of the add-on do you have installed? 
- What version of chrome? 
- What resolution are your screens?

**Comment by dunklesToast** [comment]
@fcapano 
* EditThisCookie 1.4.4
* Chrome 65.0.3325.181 (Official Build)
* Screen is 2560*1080 (21:9 Widescreen)

**Comment by fcapano** [comment]
Thanks for the data... Interesting,I've found a Chromium bug that may be causing this issue.
https://bugs.chromium.org/p/chromium/issues/detail?id=428044#c13
I'll implement one of the proposed solutions and hopefully it will tackle the issue.

**Comment by dunklesToast** [comment]
The Issue seems to be related because the correct content flashes before it gets shrinked to the small size! Would be great if you make it work again :)

**Comment by omarchh** [comment]
I have the same issue, here's my info:

- Chrome : Version 65.0.3325.181 (Official Build) (64-bit)
- EditThisCookie : Version 1.4.5
- Screen : 2560 x 1044

I get the plugin to open and blink somehow to get smaller and show only around 100px tall, I can scroll inside of it tho but I can't see the top info.
I managed to see the cookies with the right click option menu (it opens a new tab) and that's how I am working right now. Also I have a Windows Laptop, I am going to try to open it there to see if it has the same behavior

**Comment by fcapano** [comment]
I've submitted a patch taken from https://bugs.chromium.org/p/chromium/issues/detail?id=428044#c35
I couldn't reproduce the issue on my PC, so could anyone affected checkout the branch **small_popup_workaround** and confirm whether this solves or mitigates the issue?

**Comment by cknave** [comment]
@fcapano I tried af08b3697866dd43b274aa0af731499821f60210 but it still has the issue for me on Chrome 65.0.3325.181 on macOS.

**Comment by davididas** [comment]
@cknave can you please test out  #207 on your system? thanks!

**Comment by cknave** [comment]
@davididas This seems to work, I could not get the bug to happen on a5b92713402e6a9883adefc8c2f842e6dc0d927f
