### ISSUE TITLE
Extension unusable in chrome 68 Incognito windows

### ISSUE THREAD

**Issue by culmer30** [fcapano/Edit-This-Cookie#229]
I've noticed that the extension doesn't work as expected in chrome incognito windows. I noticed it not working with chrome 68, but it may have been broken since before then. Works fine with non-incognito windows though.

Often times when looking for cookies on incognito windows you'll see "No cookies here" but if you look at the chrome dev tools Application pane and find the cookies for the page you'll see there's several. Adding cookies and manipulating any cookies that do eventually show up in edit this cookie extension doesnt have any effect.

**Comment by octa** [comment]
Same thing happens to me on Chrome 68 as well, both on Mac OS and Windows. AFAIK, it used to work correctly before the Chrome 68 update.

Is there a workaround to get it to work in incognito mode?

**Comment by inlace** [comment]
Yeah, have same issue

**Comment by culmer30** [comment]
I see the chrome store got an update today - did that update include this fix?
