### ISSUE TITLE
How is this Plugin able to access HttpOnly cookies?

### ISSUE THREAD

**Issue by johnnyodonnell** [fcapano/Edit-This-Cookie#255]
Just out of curiosity, how is this plugin able to access HttpOnly cookies? I thought those cookies were inaccessible to JavaScript

**Comment by RedSparr0w** [comment]
I believe it's because of this permission:

https://github.com/ETCExtensions/Edit-This-Cookie/blob/9973ebb8dacc5b3c485aa1e4c4e0db8a84e4c9e8/manifest.json#L38

[More info here](https://developer.chrome.com/extensions/cookies)

**Comment by johnnyodonnell** [comment]
@RedSparr0w I think that is correct. Also, I ended up finding [this](https://developer.chrome.com/extensions/cookies), which is an API for accessing cookies from a Chrome extension.
