### ISSUE TITLE
localhost cookies cannot be created

### ISSUE THREAD

**Issue by fcapano** [fcapano/Edit-This-Cookie#27]
_Original author: amm...@gmail.com (December 13, 2011 19:19:13)_

<b>What steps will reproduce the problem?</b>
1. Go to http://localhost (note: you must have a webserver installed)
2. Open Edit This Cookie
3. Attempt to create a cookie

<b>What is the expected output? What do you see instead?</b>
Expected: Cookie is created.

Actual: Cookie is not created, and no error message.

<b>What version of the product are you using? On what operating system?</b>
Windows 7 x64
Chrome 15.0.874.121
Edit This Cookie v0.14.4

<b>Please provide any additional information below.</b>

_Original issue: http://code.google.com/p/editthiscookie/issues/detail?id=28_

**Comment by gabrielf** [comment]
You can set a cookie on localhost by removing the domain from the domain text field. Not very obvious but cookies cannot be set with an explicit domain on localhost. See for example: http://stackoverflow.com/questions/1134290/cookies-on-localhost-with-explicit-domain

**Comment by gabrielf** [comment]
My suggestion is that setting a cookie when on localhost should not prefill the domain field.
