### ISSUE TITLE
the latest chrome is not available to edit cookie

### ISSUE THREAD

**Issue by coder4lin** [fcapano/Edit-This-Cookie#274]
chrome version：80.0.3987.132
os：mac os 10.15.3

**Comment by sunui** [comment]
You can use [Chrome Dev](https://www.google.cn/intl/en/chrome/dev/)

**Comment by coder4lin** [comment]
> You can use [Chrome Dev](https://www.google.cn/intl/en/chrome/dev/)

thank you for your help, this plug-in can be used again

**Comment by adam-jones-net** [comment]
I can't add new cookies either.  Same issue ?

**Comment by Raisel** [comment]
has **solution for the problem**, follows:
when creating a new cookie you must select a **LAX** option in the **SameSite** selection combo
![image](https://user-images.githubusercontent.com/6133736/94792915-0ea8c100-03b0-11eb-883f-c7e06c692ef8.png)
