### ISSUE TITLE
unable to add cookie in chrome version  80.0.3987.149

### ISSUE THREAD

**Issue by clydebear** [fcapano/Edit-This-Cookie#276]
After I update chrome to version  80.0.3987.149  .it won't work.

**Comment by joshcrogers** [comment]
I had a recent issue adding cookies as well, looks like adding a cookie to a Secure/SSL (i.e. https) site was not checking the secure box by default, so I couldn't add the cookie.  If I check this box when adding the cookie, then it worked.  Try that

**Comment by k79e** [comment]
Me too.
I think it's started from some version before 80.0.3987.149.

**Comment by andiblas** [comment]
Same issue here too. Inspecting the extension i see this error when i try to save the cookie on https://google.com.

![image](https://user-images.githubusercontent.com/11488736/77767927-88867900-7020-11ea-8779-4eb3f17844e9.png)

OS: macOs Catalina 10.15.3 (19D76)
Chrome Version 80.0.3987.149 (Official Build) (64-bit)

**Comment by dalejung** [comment]
Chrome has been updated to not allow setting SameSite=None cookies unless you have Secure checked. So the default set of values when adding a new cookie is invalid now. I think most cases just selecting Lax is fine.

PR:
https://github.com/ETCExtensions/Edit-This-Cookie/pull/278

**Comment by dalejung** [comment]
@clydebear can you keep this issue open until a new release? Hopefully keep dupe issues from being raised.

**Comment by Raisel** [comment]
has **solution for the problem**, follows:
when creating a new cookie you must select a **LAX** option in the **SameSite** selection combo
![image](https://user-images.githubusercontent.com/6133736/94792915-0ea8c100-03b0-11eb-883f-c7e06c692ef8.png)

**Comment by 0xdra** [comment]
> has **solution for the problem**, follows:
> when creating a new cookie you must select a **LAX** option in the **SameSite** selection combo
> ![image](https://user-images.githubusercontent.com/6133736/94792915-0ea8c100-03b0-11eb-883f-c7e06c692ef8.png)
Too troublesome
