### ISSUE TITLE
Can't create new cookies manually

### ISSUE THREAD

**Issue by adam-jones-net** [fcapano/Edit-This-Cookie#294]
Not sure why this has occurred, was it the latest Chrome I updated to today ( 84.0.4147.135).

Whatever site I am on if I open the plugins screen, click the plus icon and add a cookie name and value, upon clicking the green tick and then checking for the cookie it never exists.

Refreshing page, clearing cache, reinstalling the plugin don't help.

**Comment by kairyou** [comment]
Currently, add new cookie must set ` SameSite=Lax`
![image](https://user-images.githubusercontent.com/544524/91008818-bdb7e700-e611-11ea-856d-bfadd95e8141.png)


PR #278

**Comment by adam-jones-net** [comment]
Thanks for clarifying
