### ISSUE TITLE
Chrome 85.0.4183.83 - 64 bits - I can't create new cookies

### ISSUE THREAD

**Issue by Raisel** [fcapano/Edit-This-Cookie#295]
I have used your extension for many years, it has always worked perfectly. but now I can't create new cookies. I can still edit cookies. no new cookies are saved.
Chrome is up to date
Version 85.0.4183.83 (Official version) 64 bits

**Comment by MarvelWild** [comment]
same issue here, cannot add new cookie. worked like month ago.
Version 85.0.4183.102 (Official Build) (64-bit)

**Comment by jamesmonia** [comment]
Also experiencing this

**Comment by cmarcelo-tkww** [comment]
same here

**Comment by dalejung** [comment]
#285

**Comment by JessicaDewing** [comment]
This is a big inconvenience. I used this feature all the time for testing changed behind a production cookie. When is a fixed planed?

**Comment by AntoineLemaire** [comment]
Same here 
Chrome 84.0.4147.135
Chromium 85.0.4183.121

**Comment by Raisel** [comment]
has **solution for the problem**, follows:
when creating a new cookie you must select a **LAX** option in the **SameSite** selection combo
![image](https://user-images.githubusercontent.com/6133736/94792915-0ea8c100-03b0-11eb-883f-c7e06c692ef8.png)
