### ISSUE TITLE
Malware detected

### ISSUE THREAD

**Issue by megaroeny** [fcapano/Edit-This-Cookie#302]
Today, my MS Edge browser v87 flagged this extension with malware. Microsoft has even removed it from their extension store.

See:
![image](https://user-images.githubusercontent.com/1559447/100764837-c9f7d100-33c4-11eb-927c-21b0ff6a72ef.png)

Until then, I'll be using another extension. And for some reason, Google hasn't taken it down yet. I trust MS security more than Google's anyway.

**Comment by fcapano** [comment]
I'm the creator of EditThisCookie, thanks for letting me know of this.

The reason Google hasn't taken it down it that it does not contain malware. You can check the extension' source code yourself if you wish to do so.

I did not create the listing for Microsoft Edge, and officially I only support Google Chrome and Opera, so I have no insight into what has happened and why it was listed as malware.

**Comment by megaroeny** [comment]
> I'm the creator of EditThisCookie, thanks for letting me know of this.
> 
> The reason Google hasn't taken it down it that it does not contain malware. You can check the extension' source code yourself if you wish to do so.
> 
> I did not create the listing for Microsoft Edge, and officially I only support Google Chrome and Opera, so I have no insight into what has happened and why it was listed as malware.

Woah, so how is it listed on the Edge store? Is MS doing that themselves? Maybe contact them about it, it's not my extension 😂 Something in your code they don't like. I'm not an engineer, so I can't look through code as an option. Sorry
