### ISSUE TITLE
Старая ссылка на расширение

### ISSUE THREAD

**Issue by TimkaMB** [fcapano/Edit-This-Cookie#364]
Заменить ссылку `https://chrome.google.com/webstore/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg/reviews` на `https://chromewebstore.google.com/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg` в кнопке "Оцените EditThisCookie".

**Comment by Timka251** [comment]
![image](https://github.com/ETCExtensions/Edit-This-Cookie/assets/99553007/5bbb77c6-411c-448e-9d46-680ed82c2912)
