### ISSUE TITLE
Why was this removed from the Chrome Web Store?

### ISSUE THREAD

**Issue by ylluminate** [fcapano/Edit-This-Cookie#370]
Anyone have any news on why this has been removed from the Chrome Web Store?

**Comment by amit139313** [comment]
This extension is used to spread malware. The source code in chrome web store was different from what is present in github. It was also knows to inject ads, steal saved passwords and cookies etc.

https://malwaretips.com/blogs/remove-editthiscookie-chrome-extension/

**Comment by fcapano** [comment]
Hi @amit139313 , I'm the sole developer of EditThisCookie.

Thanks for bringing this up, I can vouch for the fact that that article is absolutely made up. I have tried to contact the website multiple times many years ago, and they haven't been helpful at all.

The extension is absolutely NOT malware. But don't take my word for it.
It's all Javascript, CSS and HTML, and you can inspect the source code in your computer after installing it if you wish to do so. EditThisCookie has been trusted by  millions of users, for over a decade.


@ylluminate to your point, unfortunately I have missed some notifications from Google mentioning how it violates some of their new rules, specifically as mentioned by Google:

- Violation reference ID: [Yellow Argon](https://developer.chrome.com/docs/webstore/troubleshooting/#keyword-stuffing)
  - Violation: Having [excessive and/or irrelevant keywords](https://developer.chrome.com/webstore/spam-faq#keyword-spam) in the item's description

I am now looking into this to get the extension back on Chrome Web Store.

**Comment by Hacksore** [comment]
So it was removed for using excessive keywords?

The Opera extension is still up.
https://addons.opera.com/en/extensions/details/edit-this-cookie/

Chrome store wayback link:
https://web.archive.org/web/20240322070252/https://chromewebstore.google.com/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg

I was concerned that something more serious is going on 😅.

**Comment by krrr-crypto** [comment]
I am surprised by the developer why he does not fix it. He has been ignoring everyone since 2018. Look at the top. He has Issues
181 When Google deleted him, I see him speaking today

**Comment by i386-unofficial** [comment]
Can we have some instructions to compile it in order to skip the chrome web store?

**Comment by Hacksore** [comment]
Not supporting [manifest v3](https://developer.chrome.com/docs/extensions/develop/migrate/what-is-mv3) will get you removed from the store as well [according to Google](https://support.google.com/chrome/a/thread/257420994/upgrading-chrome-app-to-manifest-v3?hl=en#:~:text=All%20existing%20extensions%20will%20need%20to%20be%20migrated%20to%20V3%20by%20June%202024%20to%20continue%20working.%20Beginning%20June%202024%2C%20Chrome%20will%20gradually%20disable%20Manifest%20V2%20extensions%20running%20in%20the%20browser.).
https://github.com/ETCExtensions/Edit-This-Cookie/blob/9973ebb8dacc5b3c485aa1e4c4e0db8a84e4c9e8/manifest.json#L47

**Comment by Hacksore** [comment]
@86-hachiroku 

> Can we have some instructions to compile it in order to skip the chrome web store?

- Download the code from github as a zip
- Extract the zip somewhere
- "Load unpacked" in chrome://extensions
- Select the unzipped folder

**Comment by Hacksore** [comment]
It's back on the Chrome Web Store now but it has a warning banner most likely for https://github.com/ETCExtensions/Edit-This-Cookie/issues/370#issuecomment-2241356789.

https://chromewebstore.google.com/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg

![image](https://github.com/user-attachments/assets/77cf9c29-2f6f-4b99-953c-4f5ac14f193b)

**Comment by ylluminate** [comment]
Glad to see things becoming sane again. I've not found any comparable extensions that line up with this tool, so hopefully we can see some updates that will resolve Google's own insanity and idiocy. Google itself is a massive scam with "always do evil" as its motto - learned the hard way after having them con me out of investing in one of their products to only have it killed out from under us after an enormous investment of time and money. Google == pure evil.

**Comment by fcapano** [comment]
It's sad but I have to partially agree with you @ylluminate. I've grown quite disillusioned with Google as a company. 

Zero warning from them and extremely vague and unhelpful messages, left me wondering what I needed to do to get the extension back on the store, and had to update the description a couple more times. 

The last message sey sent me was literally the following:
`Violating content:
Cookies`
So I sacrificed a few of the occurrences of the word "cookies" from the description praying that that would make the Google gods happy. I suppose it worked. Oh, and I wasn't even notified it was reinstated, I found out from these comments. 

Now off to figure out how manifest V3 will work for ETC...

**Comment by MakcStudio** [comment]
The extension page right now is still not available, how soon should we expect the extension to come back to google?

> It's sad but I have to partially agree with you @ylluminate. I've grown quite disillusioned with Google as a company.
> 
> Zero warning from them and extremely vague and unhelpful messages, left me wondering what I needed to do to get the extension back on the store, and had to update the description a couple more times.
> 
> The last message sey sent me was literally the following: `Violating content: Cookies` So I sacrificed a few of the occurrences of the word "cookies" from the description praying that that would make the Google gods happy. I suppose it worked. Oh, and I wasn't even notified it was reinstated, I found out from these comments.
> 
> Now off to figure out how manifest V3 will work for ETC...

**Comment by dmdabbs** [comment]
I restarted Chrome this am to discover ETC had been disabled. Will the PR addressing M3 be merged or is there a functional fork? Or must one search for an alternative?

**Comment by onassar** [comment]
Does anyone here want to band together and build our own open source version?

**Comment by brandenmullin2-maker** [comment]
What can I use that's like cookies
