### ISSUE TITLE
Add new cookie - does not work

### ISSUE THREAD

**Issue by fcapano** [fcapano/Edit-This-Cookie#39]
_Original author: GuyBelli...@gmail.com (June 21, 2012 21:20:15)_

<b>What steps will reproduce the problem?</b>
1. Click Add new cookie in 'advanced' tools
2. Enter name, value, domain and expiry date in future
3. Click [Submit Changes] ...way at the bottom? 

<b>What is the expected output? What do you see instead?</b>
A new cookie with the entered name and value and expiry date should be listed. 

<b>What version of the product are you using? On what operating system?</b>
Latest EditThisCookie from webstore Chrome 19 on  Win7 32bit. 

<b>Please provide any additional information below.</b>
New cookie does not show even after clicking the refresh link. 
Also  editing a cookie and changing the domain and date  does not work. The cookie just disappears!? 

_Original issue: http://code.google.com/p/editthiscookie/issues/detail?id=40_

**Comment by barakt11** [comment]
I am trying to add new cookie as well but its not working.
doing to a local server running on localhost:9999

**Comment by Maktm** [comment]
Importing a cookie simply does nothing as of the latest version on Chrome (Windows 7). Exporting does nothing also on Firefox (ESR & Quantum) (Debian) even though a pop-up saying "Copied to clipboard!" shows up.

**Comment by sagar74132** [comment]
Can't add Cookies using Import Button. It does nothing.
Errors: (SS Attached)
![image](https://user-images.githubusercontent.com/29474428/48677281-6a8d4680-eb98-11e8-89f6-04624c647aee.png)
