### ISSUE TITLE
50% CPU usage

### ISSUE THREAD

**Issue by fcapano** [fcapano/Edit-This-Cookie#46]
_Original author: filar...@gmail.com (September 07, 2012 07:31:56)_

Hello,
I've noticed that since last updates, ETC often brings up the CPU usage to 50-60% (I can see this from Chrome Task Manager).

I have been forced to disable it otherwise my PC becomes very slow.
I'm running 21.0.1180.89 and Windows 7 SP1 32-bit

_Original issue: http://code.google.com/p/editthiscookie/issues/detail?id=47_

**Comment by JonasNo** [comment]
This function gets into an infinite loop:
background.js line 60 -> "chrome.cookies.onChanged.addListener( function(changeInfo) {"

changeinfo:
cause: "overwrite"
cookie: Object
removed: true

The function "chrome.cookies.get" at line 84 executes the callback function with currentCookie = null.
That cause an exception in "compareCookies" line 89.
"cookie_helpers.js:99 Cannot read property 'name' of null"

The function "compareCookies" returns false after the exception. Than calls "chrome.cookies.set(newCookie);" at line 92 in background.js

This causes an infinite loop.

"chrome.cookies.set" cause "chrome.cookies.onChanged" to be called and it repeats.

The infinite loop starts somehow when chrome is idle for a period of time.

**Comment by fcapano** [comment]
I don't think there's been any report regarding this in a long time, I'll close this issue.
