### ISSUE TITLE
Trying to edit cookie expiration date, without success

### ISSUE THREAD

**Issue by ghost** [fcapano/Edit-This-Cookie#59]
Hello, I'm trying to edit the session expiration date, unchecking the "session" tab of a PHPSESSID cookie, without success. I also tried protecting the cookie, but no change.
It normally expires even if I don't close the tab, that's why I wonder how to change the limit.

Here's the web, just in case (webunlp.unlp.edu.ar)

**Comment by lbigtonyl** [comment]
I know this post is (very) old but you probably shouldn't show the Cookie DATA without blurring some of it out
