### ISSUE TITLE
Add ability to use wildcards

### ISSUE THREAD

**Issue by fcapano** [fcapano/Edit-This-Cookie#8]
_Original author: lordsargon@gmail.com (February 02, 2011 18:49:38)_

If I am overlooking this functionality, I apologize.

It would be helpful to be able to use wildcards when adding blocked cookies. I tried using them, but the process doesn't appear to work.

_Original issue: http://code.google.com/p/editthiscookie/issues/detail?id=8_

**Comment by djbclark** [comment]
Looks like #83 implements this, but hasn't yet made it into the version up on the chrome store.
