### ISSUE TITLE
GUI is not rendered properly

### ISSUE THREAD

**Issue by slavafomin** [fcapano/Edit-This-Cookie#85]
Hey there!

I have a problem with this great plugin after an interface update.

Please see the screenshot:
![cookiebug](https://cloud.githubusercontent.com/assets/1702725/2631401/7abdb1b0-be58-11e3-99af-646c886cf6c9.png)

As you can see, interface is not rendered properly.

I'm running it with `Google Chrome Version 33.0.1750.152` and latest `Xubuntu Linux 13.10` with Linux kernel `3.11.9-031109-generic, x86_64` and `XFCE 4.10`.

Some days ago, I could get it to render after opening GUI for 3-4 times. But now I can't get it to work anyhow.

So right now plugin is completely unusable to me. Could you fix this please? And maybe you could recommend me another plugin to use during this downtime?

Thank you!

**Comment by fcapano** [comment]
I'll pin this down to problems in the graphics stack / system setup / chrome

**Comment by slavafomin** [comment]
Three years from the original issue — I can confirm that it's working great :)

Keep up the good work!
