### ISSUE TITLE
No auth cookie?

### ISSUE THREAD

**Issue by brolmongo** [fcapano/Edit-This-Cookie#96]
Hi there

Trying out your add-on with hopes of getting an authentification cookie. Unfortunately I'm not seeing them. Is there any setting on my part that is blocking them or is it not supported by editthiscookie?

Thanks

**Comment by solocommand** [comment]
@brolmongo Can you provide more details here? EditThisCookie should have no problem displaying any cookies, so long as they are properly set. What exactly are you looking for?
